// Constants
package EvolutionEngine

type FilterType int

const (
	FILTER_DENY FilterType = iota
	FILTER_ALLOW
	FILTER_MODIFY
	FILTER_ACTION_REPLACE
	FILTER_ACTION_EXECUTE_BEFORE
	FILTER_ACTION_EXECUTE_AFTER
)

type FilterSourcePrototype int

const (
	FILTER_SOURCE_PARAMETER_PLAYER FilterSourcePrototype = iota
	FILTER_SOURCE_PARAMETER_PROPERTY 
	FILTER_SOURCE_PARAMETER_SOURCE_CREATURE
	FILTER_SOURCE_PARAMETER_TARGET_CREATURE
	FILTER_SOURCE_PARAMETER_CREATURE
	FILTER_SOURCE_PARAMETER_TRAIT
	FILTER_SOURCE_PARAMETER_ALL_PLAYERS
	FILTER_SOURCE_PARAMETER_LEFT_CREATURE
	FILTER_SOURCE_PARAMETER_RIGHT_CREATURE
	FILTER_SOURCE_PARAMETER_PAIR
	FILTER_SOURCE_PARAMETER_ANY_FOOD
	FILTER_SOURCE_PARAMETER_ALL_FOOD
	FILTER_SOURCE_PARAMETER_FOOD_AND_FAT_LIMIT
	FILTER_SOURCE_PARAMETER_FOOD_AND_FAT
	FILTER_SOURCE_PARAMETER_ALL_FOOD_AND_FAT
	FILTER_SOURCE_PARAMETER_PHASE
	FILTER_SOURCE_PARAMETER_SOURCE
	FILTER_SOURCE_PARAMETER_CREATURE_PROPERTIES
	FILTER_SOURCE_PARAMETER_FOOD_BANK_COUNT
	FILTER_SOURCE_PARAMETER_CURRENT_PLAYER
	FILTER_SOURCE_PARAMETER_ONE_OF_CURRENT_PLAYER_CARDS
	FILTER_SOURCE_PARAMETER_ONE_OF_CURRENT_PLAYER_CARDS_PROPERTIES
	FILTER_SOURCE_PARAMETER_ONE_OF_CURRENT_PLAYER_CREATURES_PAIR
	FILTER_SOURCE_PARAMETER_ONE_OF_CURRENT_PLAYER_CREATURES
	FILTER_SOURCE_PARAMETER_ONE_OF_CREATURES
	FILTER_SOURCE_PARAMETER_BANK_CARDS_COUNT
)

func (t FilterSourcePrototype) GoString() string {
	switch t {
		case FILTER_SOURCE_PARAMETER_PHASE:
			return "Phase"
		case FILTER_SOURCE_PARAMETER_PLAYER:
			return "Player"
		case FILTER_SOURCE_PARAMETER_PROPERTY:
			return "Property"
		case FILTER_SOURCE_PARAMETER_SOURCE_CREATURE:
			return "Source creature"
		case FILTER_SOURCE_PARAMETER_TARGET_CREATURE:
			return "Target creature"
		case FILTER_SOURCE_PARAMETER_CREATURE:
			return "Creature"
		case FILTER_SOURCE_PARAMETER_TRAIT:
			return "Trait"
		case FILTER_SOURCE_PARAMETER_ALL_PLAYERS:
			return "All players"
		case FILTER_SOURCE_PARAMETER_RIGHT_CREATURE:
			return "Second creature in pair"
		case FILTER_SOURCE_PARAMETER_LEFT_CREATURE:
			return "First creature in pait"
		case FILTER_SOURCE_PARAMETER_ANY_FOOD:
			return "Any food"
		case FILTER_SOURCE_PARAMETER_ALL_FOOD:
			return "All food"
		case FILTER_SOURCE_PARAMETER_FOOD_AND_FAT_LIMIT:
			return "Food and fat"
		case FILTER_SOURCE_PARAMETER_SOURCE:
			return "Source"
		case FILTER_SOURCE_PARAMETER_PAIR:
			return "Pair"
		case FILTER_SOURCE_PARAMETER_CREATURE_PROPERTIES:
			return "Creature properties"
		case FILTER_SOURCE_PARAMETER_FOOD_BANK_COUNT:
			return "Food in bank"
		case FILTER_SOURCE_PARAMETER_CURRENT_PLAYER:
			return "Current player"
		case FILTER_SOURCE_PARAMETER_ONE_OF_CURRENT_PLAYER_CARDS:
			return "One of current player cards"
		case FILTER_SOURCE_PARAMETER_ONE_OF_CURRENT_PLAYER_CARDS_PROPERTIES:
			return "One of players properties"
		case FILTER_SOURCE_PARAMETER_ONE_OF_CURRENT_PLAYER_CREATURES_PAIR:
			return "Creatures pair"
		case FILTER_SOURCE_PARAMETER_ONE_OF_CURRENT_PLAYER_CREATURES:
			return "Player creature"
		case FILTER_SOURCE_PARAMETER_ONE_OF_CREATURES:
			return "One of creatures"
		default:
			return string(t)
	}
}

type TraitType string

const (
	TRAIT_PASS TraitType = "Pass"
	TRAIT_USED = "Used"
	TRAIT_TOOK_FOOD = "Food"
	TRAIT_SHARP_VISION = "Sharp vision"
	TRAIT_CAMOUFLAGE = "Camouflage"
	TRAIT_BURROWING = "Burowing"
	TRAIT_FED = "Fed"
	TRAIT_PAIR = "Pair"
	TRAIT_FAT_TISSUE = "Fat tissue"
	TRAIT_FOOD = "Food"
	TRAIT_ADDITIONAL_FOOD = "Additional food"
	TRAIT_REQUIRE_FOOD = "Require food"
	TRAIT_FAT = "Fat"
	TRAIT_SYMBIOSIS = "Symbiosys"
	TRAIT_PIRACY = "Piracy"
	TRAIT_HIGH_BODY_WEIGHT = "High body weight"
	TRAIT_GRAZING = "Grazing"
	TRAIT_TAIL_LOSS = "Tail loss"
	TRAIT_PARASITE = "Parasite"
	TRAIT_CARNIVOROUS = "Carnivorous"
	TRAIT_BURNED_FAT = "Burned fat"
	TRAIT_ADDITIONAL_GET_FOOD_FROM_BANK = "Additional get food from bank"
	TRAIT_HIBERNATION = "Hibernation"
	TRAIT_POISONOUS = "Poisonous"
	TRAIT_COMMUNICATION = "Communication"
	TRAIT_SCAVENGER = "Scavenger"
	TRAIT_SWIMMING = "Swimming"
	TRAIT_COOPERATION = "Cooperation"
	TRAIT_MIMICRY = "Mimicry"
	TRAIT_RUNNING = "Running"
)

type PhaseType string

const (
	PHASE_DEVELOPMENT PhaseType = "Development"
	PHASE_FOOD_BANK_DETERMINATION = "Food bank determination"
	PHASE_FEEDING = "Feeding"
	PHASE_EXTINCTION = "Extinction"
	PHASE_FINAL = "Final"
)

type ActionType string

const (
	ACTION_SEQUENCE ActionType = "Sequence"
	ACTION_SELECT = "Select"
	ACTION_START_TURN = "Start turn"
	ACTION_NEXT_PLAYER = "Next player"
	ACTION_ADD_CREATURE = "Add creature"
	ACTION_ADD_SINGLE_PROPERTY = "Add single property"
	ACTION_ADD_PAIR_PROPERTY = "Add pair property"
	ACTION_PASS = "Pass"
	ACTION_END_TURN = "End turn"
	ACTION_NEW_PHASE = "New phase"
	ACTION_ADD_TRAIT = "Add trait"
	ACTION_REMOVE_TRAIT = "Remove trait"
	ACTION_ADD_FILTERS = "Add filters"
	ACTION_ATTACK = "Attack"
	ACTION_DETERMINE_FOOD_BANK = "Determine food bank"
	ACTION_REMOVE_CREATURE = "Remove creature"
	ACTION_REMOVE_CARD = "Remove card"
	ACTION_REMOVE_PROPERTY = "Remove property"
	ACTION_GET_FOOD_FROM_BANK = "Get food from bank"
	ACTION_BURN_FAT = "Burn fat"
	ACTION_PIRACY = "Piracy"
	ACTION_DESTROY_BANK_FOOD = "Destroy bank food"
	ACTION_SELECT_FROM_AVAILABLE_ACTIONS = "Select from allowed actions"
	ACTION_EXTINCT = "Extinct"
	ACTION_TAKE_CARDS = "Take cards"
	ACTION_GAIN_FOOD = "Gain food"
	ACTION_GAIN_ADDITIONAL_FOOD = "Gain additional food"
	ACTION_EAT = "Eat"
	ACTION_HIBERNATE = "Hibernate"
	ACTION_RANDOM_ATTACK = "Random attack"
	ACTION_SCAVENGE = "Scavenge"
)

type ArgumentName string

const (
	PARAMETER_PROPERTY ArgumentName = "Property"
	PARAMETER_PHASE = "Phase"
	PARAMETER_PLAYER = "Player"
	PARAMETER_PAIR = "Pair"
	PARAMETER_CARD = "Card"
	PARAMETER_ACTIONS = "Actions"
	PARAMETER_CREATURE = "Creature"
	PARAMETER_TRAIT = "Trait"
	PARAMETER_SOURCE = "Source"
	PARAMETER_FILTERS = "Filters"
	PARAMETER_SOURCE_CREATURE = "Source creature"
	PARAMETER_TARGET_CREATURE = "Taget creature"
	PARAMETER_COUNT = "Count"
)

type AccessorMode int

const (
	ACCESSOR_MODE_ONE_OF_CREATURE_PROPERTIES AccessorMode = iota
	ACCESSOR_MODE_CREATURE_OWNER
	ACCESSOR_MODE_PROPERTY_OWNER
	ACCESSOR_MODE_CREATURES
)

type Type int

const (
	TYPE_CREATURE Type = iota
	TYPE_PROPERTY
)